// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVzePnOttcS_YatEJ-CMVeqWzEN7vwFyk',
    appId: '1:216927959980:web:81c6e1d514a4787bce1809',
    messagingSenderId: '216927959980',
    projectId: 'opps-85fe4',
    authDomain: 'opps-85fe4.firebaseapp.com',
    storageBucket: 'opps-85fe4.firebasestorage.app',
    measurementId: 'G-0YVTBV7R5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEP80l3QszoKmNdNYWkPr-fC7m11Ev9wc',
    appId: '1:216927959980:android:bc74a4036b2ba059ce1809',
    messagingSenderId: '216927959980',
    projectId: 'opps-85fe4',
    storageBucket: 'opps-85fe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGc9Q_jKtpOwCYCaexwQmG_62hcwkTVlA',
    appId: '1:216927959980:ios:af5f568681e262e2ce1809',
    messagingSenderId: '216927959980',
    projectId: 'opps-85fe4',
    storageBucket: 'opps-85fe4.firebasestorage.app',
    iosBundleId: 'com.example.findjobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGc9Q_jKtpOwCYCaexwQmG_62hcwkTVlA',
    appId: '1:216927959980:ios:af5f568681e262e2ce1809',
    messagingSenderId: '216927959980',
    projectId: 'opps-85fe4',
    storageBucket: 'opps-85fe4.firebasestorage.app',
    iosBundleId: 'com.example.findjobs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVzePnOttcS_YatEJ-CMVeqWzEN7vwFyk',
    appId: '1:216927959980:web:443c8a878767e613ce1809',
    messagingSenderId: '216927959980',
    projectId: 'opps-85fe4',
    authDomain: 'opps-85fe4.firebaseapp.com',
    storageBucket: 'opps-85fe4.firebasestorage.app',
    measurementId: 'G-PNKSTBT5ZR',
  );
}
